"""add_progress_tracking_columns

Revision ID: 808ecbac5672
Revises: 
Create Date: 2025-10-28 02:33:21.516614

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '808ecbac5672'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('downloaded_bytes', sa.Integer(), nullable=True))
    op.add_column('downloads', sa.Column('total_bytes', sa.Integer(), nullable=True))
    op.add_column('downloads', sa.Column('download_speed', sa.Float(), nullable=True))
    op.add_column('downloads', sa.Column('eta', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'eta')
    op.drop_column('downloads', 'download_speed')
    op.drop_column('downloads', 'total_bytes')
    op.drop_column('downloads', 'downloaded_bytes')
    # ### end Alembic commands ###
