name: 📚 Documentation
description: Report documentation issues or suggest improvements
title: "[DOCS] <brief description>"
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: 🔍 What's wrong?
      description: What kind of issue is this?
      options:
        - Missing documentation
        - Outdated information
        - Unclear explanation
        - Incorrect information
        - Typos/grammar
        - Better examples needed
        - Missing screenshots/diagrams
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 What needs to be fixed?
      description: Describe the documentation issue and your suggested fix
      placeholder: |
        **The problem:**
        [What's wrong with the current documentation?]

        **The fix:**
        [What should it say instead?]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 📎 More details (optional)
      description: Any additional context or examples
      placeholder: |
        - Screenshots (drag and drop)
        - Links to similar good documentation
        - Code examples that need docs
        - Why this matters to users
    validations:
      required: false
